# Generated by Django 4.0.6 on 2022-07-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuesForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200, null=True)),
                ('ch1', models.CharField(max_length=200, null=True)),
                ('ch2', models.CharField(max_length=200, null=True)),
                ('ch3', models.CharField(max_length=200, null=True)),
                ('ch4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
