# Generated by Django 4.0.6 on 2022-07-27 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='quesform',
            name='category',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='Quizapp.category'),
        ),
    ]
