# Generated by Django 4.0.6 on 2022-07-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0003_quesform_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesform',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
