# Generated by Django 4.0.6 on 2022-07-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0004_alter_quesform_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesform',
            old_name='ch1',
            new_name='choice1',
        ),
        migrations.RenameField(
            model_name='quesform',
            old_name='ch2',
            new_name='choice2',
        ),
        migrations.RenameField(
            model_name='quesform',
            old_name='ch3',
            new_name='choice3',
        ),
        migrations.RenameField(
            model_name='quesform',
            old_name='ch4',
            new_name='choice4',
        ),
    ]
